########## Config Map: Environment Settings ##########
apiVersion: v1
kind: ConfigMap
metadata:
  name: myrabbitmq-configmap
data:
  env_rabbitmq_host: "myrabbitmq"
  env_rabbitmq_port: "5672"
  env_rabbitmq_username: Z3Vlc3Q=
  env_rabbitmq_password: Z3Vlc3Q=
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: yaowl/neo-cart:1.0.0
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: ENV_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_host
        - name: ENV_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_port
        - name: ENV_RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_username
        - name: ENV_RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_password
---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  type: NodePort
  selector:
    app: product
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 33001