########## Config Map: Environment Settings ##########
apiVersion: v1
kind: ConfigMap
metadata:
  name: myrabbitmq-configmap
data:
  env_rabbitmq_host: "myrabbitmq"
  env_rabbitmq_port: "5672"
  env_rabbitmq_username: Z3Vlc3Q=
  env_rabbitmq_password: Z3Vlc3Q=
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: yaowl/neo-order:1.0.0
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: ENV_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_host
        - name: ENV_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_port
        - name: ENV_RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_username
        - name: ENV_RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_password
---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  type: NodePort
  selector:
    app: order
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 33002
---
########## HorizontalPodAutoscaler: Autoscaling for Order ##########
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: myproducer-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 65
