apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrabbitmq
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myrabbitmq
  template:
    metadata:
      labels:
        app: myrabbitmq
    spec:
      containers:
      - name: myrabbitmq
        image: rabbitmq:3.9-management
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: myrabbitmq
spec:
  type: NodePort
  selector:
    app: myrabbitmq
  ports:
  - port: 15672
    targetPort: 15672
    nodePort: 32000
    name: "management"
  - port: 5672 
    targetPort: 5672
    nodePort: 31672
    name: "connection"
